# Generated by Django 4.2.2 on 2023-07-05 18:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('content', ckeditor.fields.RichTextField()),
                ('emails', models.FileField(upload_to='emails_base/%Y/%m/%d/')),
                ('datetime', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
